"""empty message

Revision ID: c66801a7767a
Revises: a25fbedce325
Create Date: 2020-05-21 20:34:31.824368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66801a7767a'
down_revision = 'a25fbedce325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_ibfk_2', 'product', type_='foreignkey')
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'front_user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'product', 'board', ['board_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_ibfk_1', 'product', 'board', ['board_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('product_ibfk_2', 'product', 'front_user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
