"""empty message

Revision ID: f39614bbde4a
Revises: 10daf8a017a9
Create Date: 2020-05-20 18:28:07.638887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f39614bbde4a'
down_revision = '10daf8a017a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('commenter_id', sa.String(length=100), nullable=True))
    op.drop_constraint('comment_ibfk_2', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'front_user', ['commenter_id'], ['id'])
    op.drop_column('comment', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('user_id', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_2', 'comment', 'front_user', ['user_id'], ['id'])
    op.drop_column('comment', 'commenter_id')
    # ### end Alembic commands ###
